name: Test metabolic tasks

on: [push, pull_request]

jobs:
  check-metabolictasks:
    runs-on: self-hosted
    timeout-minutes: 60

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Check essential tasks
      run: |
        /usr/local/bin/matlab -nodisplay -nosplash -nodesktop -r "addpath(genpath('.')); run('code/test/testMetabolicTasks.m', '${{ matrix.param }}'); exit;"
      env:
        matrix:
          param: [essential, verification]
